logging:
  level:
    root: info
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS}[${spring.application.name}][%thread][%X{traceId}][%X{X-B3-TraceId},%X{X-B3-SpanId},%X{X-B3-ParentSpanId}][%-5level][%logger{36}]:%msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS}[${spring.application.name}][%thread][%X{traceId}][%X{X-B3-TraceId},%X{X-B3-SpanId},%X{X-B3-ParentSpanId}][%-5level][%logger{36}]:%msg%n'
  file:
    name: './logs/${spring.application.name}_${server.port}.log'
  logfilterkey: password
  whitelist:
server:
  port: 9088
  servlet:
    encoding:
      charset: utf-8
      force: true
      enabled: true
spring:
  application:
    name: exapmle-server